In [1]:
import pandas as pd
import numpy as np

Forberedelse data

In [4]:
df = pd.read_excel('svalbard_met.xlsx')
df

,Navn,Stasjon,Tid(norsk normaltid),Homogenisert middeltemperatur (mnd)
0,Svalbard Lufthavn,SN99840,09.1898,3.8
1,Svalbard Lufthavn,SN99840,10.1898,-5.2
2,Svalbard Lufthavn,SN99840,11.1898,-11.0
3,Svalbard Lufthavn,SN99840,12.1898,-16.4
4,Svalbard Lufthavn,SN99840,01.1899,-14.8
...,...,...,...,...
1491,Svalbard Lufthavn,SN99840,2022-12-01 00:00:00,-8.4
1492,Svalbard Lufthavn,SN99840,2023-01-01 00:00:00,-3.9
1493,Svalbard Lufthavn,SN99840,2023-02-01 00:00:00,-6.7
1494,Svalbard Lufthavn,SN99840,2023-03-01 00:00:00,-5.3
1495,"Data er gyldig per 03.03.2023 (CC BY 4.0), Met...",NaN,NaN,NaN

In [5]:
df = df.dropna()
df

,Navn,Stasjon,Tid(norsk normaltid),Homogenisert middeltemperatur (mnd)
0,Svalbard Lufthavn,SN99840,09.1898,3.8
1,Svalbard Lufthavn,SN99840,10.1898,-5.2
2,Svalbard Lufthavn,SN99840,11.1898,-11.0
3,Svalbard Lufthavn,SN99840,12.1898,-16.4
4,Svalbard Lufthavn,SN99840,01.1899,-14.8
...,...,...,...,...
1490,Svalbard Lufthavn,SN99840,2022-11-01 00:00:00,-1.0
1491,Svalbard Lufthavn,SN99840,2022-12-01 00:00:00,-8.4
1492,Svalbard Lufthavn,SN99840,2023-01-01 00:00:00,-3.9
1493,Svalbard Lufthavn,SN99840,2023-02-01 00:00:00,-6.7
1494,Svalbard Lufthavn,SN99840,2023-03-01 00:00:00,-5.3

oppgave a - Use linear regression to determine the linear trend in the data from 1898 to 2023

oppgave b -  What is the slope of the regression line?