In [2]:
import pandas as pd
import numpy as np
from scipy import stats
from scipy.stats import linregress
import matplotlib.pyplot as plt
from datetime import datetime

Forberedelse data

In [3]:
df = pd.read_csv('svalbard_met.csv', sep=';', decimal=',')
df

,Navn,Stasjon,Tid(norsk normaltid),Homogenisert middeltemperatur (mnd)
0,Svalbard Lufthavn,SN99840,09.1898,3.8
1,Svalbard Lufthavn,SN99840,10.1898,-5.2
2,Svalbard Lufthavn,SN99840,11.1898,-11.0
3,Svalbard Lufthavn,SN99840,12.1898,-16.4
4,Svalbard Lufthavn,SN99840,01.1899,-14.8
...,...,...,...,...
1491,Svalbard Lufthavn,SN99840,12.2022,-8.4
1492,Svalbard Lufthavn,SN99840,01.2023,-3.9
1493,Svalbard Lufthavn,SN99840,02.2023,-6.7
1494,Svalbard Lufthavn,SN99840,03.2023,-5.3
1495,"Data er gyldig per 03.03.2023 (CC BY 4.0), Met...",NaN,NaN,NaN

Sletter alle rader med NaN verdier ved df.dropna()

In [4]:
df = df.dropna()
df

,Navn,Stasjon,Tid(norsk normaltid),Homogenisert middeltemperatur (mnd)
0,Svalbard Lufthavn,SN99840,09.1898,3.8
1,Svalbard Lufthavn,SN99840,10.1898,-5.2
2,Svalbard Lufthavn,SN99840,11.1898,-11.0
3,Svalbard Lufthavn,SN99840,12.1898,-16.4
4,Svalbard Lufthavn,SN99840,01.1899,-14.8
...,...,...,...,...
1490,Svalbard Lufthavn,SN99840,11.2022,-1.0
1491,Svalbard Lufthavn,SN99840,12.2022,-8.4
1492,Svalbard Lufthavn,SN99840,01.2023,-3.9
1493,Svalbard Lufthavn,SN99840,02.2023,-6.7
1494,Svalbard Lufthavn,SN99840,03.2023,-5.3

In [5]:
df = df.drop(range(16))

In [6]:
df.head(20)

,Navn,Stasjon,Tid(norsk normaltid),Homogenisert middeltemperatur (mnd)
16,Svalbard Lufthavn,SN99840,01.1900,-7.7
17,Svalbard Lufthavn,SN99840,02.1900,-21.2
18,Svalbard Lufthavn,SN99840,03.1900,-22.8
19,Svalbard Lufthavn,SN99840,04.1900,-12.8
20,Svalbard Lufthavn,SN99840,05.1900,-5.7
21,Svalbard Lufthavn,SN99840,06.1900,3.6
22,Svalbard Lufthavn,SN99840,07.1900,4.6
23,Svalbard Lufthavn,SN99840,08.1900,4.2
24,Svalbard Lufthavn,SN99840,09.1900,-1.0
25,Svalbard Lufthavn,SN99840,10.1900,-6.7
26,Svalbard Lufthavn,SN99840,11.1900,-13.7
27,Svalbard Lufthavn,SN99840,12.1900,-18.2
28,Svalbard Lufthavn,SN99840,01.1901,-11.2
29,Svalbard Lufthavn,SN99840,02.1901,-26.6
30,Svalbard Lufthavn,SN99840,03.1901,-17.2
31,Svalbard Lufthavn,SN99840,04.1901,-11.5
32,Svalbard Lufthavn,SN99840,05.1901,-5.8
33,Svalbard Lufthavn,SN99840,06.1901,3.2
34,Svalbard Lufthavn,SN99840,07.1901,6.1
35,Svalbard Lufthavn,SN99840,08.1901,4.5

In [7]:
y = df['Homogenisert middeltemperatur (mnd)']
y

16      -7.7
17     -21.2
18     -22.8
19     -12.8
20      -5.7
        ...
1490    -1.0
1491    -8.4
1492    -3.9
1493    -6.7
1494    -5.3
Name: Homogenisert middeltemperatur (mnd), Length: 1479, dtype: float64

In [8]:
x = df['Tid(norsk normaltid)']
x

16      01.1900
17      02.1900
18      03.1900
19      04.1900
20      05.1900
         ...
1490    11.2022
1491    12.2022
1492    01.2023
1493    02.2023
1494    03.2023
Name: Tid(norsk normaltid), Length: 1479, dtype: object

In [9]:
x['Tid'] = pd.to_datetime(x['Tid'])
x['Tid_num'] = (x['Tid'] - x['Tid'].min()).dt.days

KeyError: 'Tid'

oppgave a - Use linear regression to determine the linear trend in the data from 1898 to 2023

In [ ]:
# Perform linear regression
slope, intercept, r_value, p_value, std_err = linregress(x,y)

# Create the regression line
regression_line = slope * y['Tid(norsk normaltid)_num'] + intercept

# Plot the data points and regression line
plt.scatter(y['Tid(norsk normaltid)'], y['Homogenisert middeltemperatur (mnd)'], label='Data')
plt.plot(y['Tid(norsk normaltid)'], regression_line, color='red', label='Linear Regression')

plt.xlabel('Date')
plt.ylabel('Temperature')
plt.title('Linear Regression of Temperature over Time')
plt.legend()
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

KeyError: 'Tid(norsk normaltid)'

oppgave b -  What is the slope of the regression line?